### ISSUE TITLE
Cannot get the test project to work

### ISSUE THREAD

**Issue by PhilAndrew** [muuki88/sbt-slick#2]
I'm on Windows, does that make a difference?

Clone the test project from your git, type sbt then

```
> slickGenTables
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:2.10.4 -> 2.10.5
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[warn] Trying to run slick code generation on no database
[info] Running slick.codegen.SourceCodeGenerator slick.driver.H2Driver org.h2.Dr
iver jdbc:h2:mem:test;INIT=runscript from 'h2.create.sql' C:\home\sbt-slick-mast
er\test-project\target\scala-2.10\src_managed\main models
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
[error] (run-main-0) org.h2.jdbc.JdbcSQLException: Schema "TEST_DB" already exis
ts; SQL statement:
[error] CREATE SCHEMA TEST_DB [90078-170]
[trace] Stack trace suppressed: run last *:slickGenTables for the full output.
[trace] Stack trace suppressed: run last *:slickGenTables for the full output.
[error] (*:slickGenTables) Nonzero exit code: 1
[error] Total time: 1 s, completed Feb 29, 2016 8:35:51 PM
>
> last *:slickGenTables
[warn] Trying to run slick code generation on no database
[info] Running slick.codegen.SourceCodeGenerator slick.driver.H2Driver org.h2.Dr
iver jdbc:h2:mem:test;INIT=runscript from 'h2.create.sql' C:\home\sbt-slick-mast
er\test-project\target\scala-2.10\src_managed\main models
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug]         C:\Users\philip\.ivy2\cache\com.typesafe.slick\slick_2.10\bundle
s\slick_2.10-3.1.0.jar
[debug]         C:\Users\philip\.ivy2\cache\org.scala-lang\scala-library\jars\sc
ala-library-2.10.5.jar
[debug]         C:\Users\philip\.ivy2\cache\org.slf4j\slf4j-api\jars\slf4j-api-1
.7.10.jar
[debug]         C:\home\software\activator-dist-1.3.5\repository\com.typesafe\co
nfig\1.2.1\bundles\config.jar
[debug]         C:\home\software\activator-dist-1.3.5\repository\org.reactivestr
eams\reactive-streams\1.0.0\jars\reactive-streams.jar
[debug]         C:\Users\philip\.ivy2\cache\com.typesafe.slick\slick-codegen_2.1
0\jars\slick-codegen_2.10-3.1.0.jar
[debug]         C:\home\software\activator-dist-1.3.5\repository\com.h2database\
h2\1.3.170\jars\h2.jar
[debug]         C:\Users\philip\.ivy2\cache\mysql\mysql-connector-java\jars\mysq
l-connector-java-5.1.34.jar
[debug] Waiting for thread run-main-0 to terminate.
[error] (run-main-0) org.h2.jdbc.JdbcSQLException: Schema "TEST_DB" already exis
ts; SQL statement:
[error] CREATE SCHEMA TEST_DB [90078-170]
org.h2.jdbc.JdbcSQLException: Schema "TEST_DB" already exists; SQL statement:
CREATE SCHEMA TEST_DB [90078-170]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
        at org.h2.message.DbException.get(DbException.java:169)
        at org.h2.message.DbException.get(DbException.java:146)
        at org.h2.command.ddl.CreateSchema.update(CreateSchema.java:45)
        at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:77)

        at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:56)
        at org.h2.command.CommandContainer.update(CommandContainer.java:75)
        at org.h2.command.Command.executeUpdate(Command.java:230)
        at org.h2.engine.Engine.openSession(Engine.java:193)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:138)
        at org.h2.engine.Engine.createSession(Engine.java:121)
        at org.h2.engine.Engine.createSession(Engine.java:28)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.jav
a:305)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:109)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
        at org.h2.Driver.connect(Driver.java:72)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:98)
        at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.s
cala:64)
        at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:
415)
        at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
        at slick.jdbc.JdbcBackend$BaseSession.metaData$lzycompute(JdbcBackend.sc
ala:420)
        at slick.jdbc.JdbcBackend$BaseSession.metaData(JdbcBackend.scala:420)
        at slick.jdbc.meta.MTable$$anonfun$getTables$1.apply(MTable.scala:28)
        at slick.jdbc.meta.MTable$$anonfun$getTables$1.apply(MTable.scala:28)
        at slick.jdbc.ResultSetInvoker$$anon$4.createResultSet(ResultSetInvoker.
scala:36)
        at slick.jdbc.ResultSetInvoker.iteratorTo(ResultSetInvoker.scala:19)
        at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
        at slick.jdbc.ResultSetInvoker.foreach(ResultSetInvoker.scala:14)
        at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.sc
ala:22)
        at slick.jdbc.ResultSetAction$$anon$1.run(ResultSetInvoker.scala:42)
        at slick.jdbc.ResultSetAction$$anon$1.run(ResultSetInvoker.scala:42)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(Dat
abaseComponent.scala:237)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseCompo
nent.scala:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[debug]         Thread run-main-0 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Interrupting thread Abandoned connection cleanup thread
[debug]         Interrupted Abandoned connection cleanup thread
[debug] Interrupting thread ForkJoinPool-1-worker-5
[debug]         Interrupted ForkJoinPool-1-worker-5
[debug] Interrupting thread Thread-1
[debug]         Interrupted Thread-1
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1874)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1874)
        at scala.Option.foreach(Option.scala:236)
        at sbt.BuildCommon$class.toError(Defaults.scala:1874)
        at sbt.package$.toError(package.scala:4)
        at de.mukis.sbt.slick.SlickCodeGenPlugin$$anonfun$projectSettings$7.appl
y(SlickCodeGenPlugin.scala:39)
        at de.mukis.sbt.slick.SlickCodeGenPlugin$$anonfun$projectSettings$7.appl
y(SlickCodeGenPlugin.scala:22)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:slickGenTables) Nonzero exit code: 1
>
```

**Comment by muuki88** [comment]
Looks like the H2 table already exists

```
CREATE SCHEMA TEST_DB [90078-170]
org.h2.jdbc.JdbcSQLException: Schema "TEST_DB" already exists; SQL statement:
CREATE SCHEMA TEST_DB [90078-170]
```

can you figure out why? is it not in-memory

**Comment by muuki88** [comment]
Looks like the [schema.sql](https://github.com/muuki88/sbt-slick/blob/master/test-project/h2.create.sql) has no `IF NOT EXISTS` clause.

**Comment by PhilAndrew** [comment]
It seems not your problem, I don't know the cause of the problem but the problem is that the schema appears to be applied more than once.
It also happens on the other projects that use Slick generate tables, I tried the others as well.

So I have to adjust my SQL to CREATE TABLE IF NOT EXISTS
